license:
  spdx: GPL-3.0

pipeline:
  # run unit-tests and check-cves in parallel so that a failure in unit-tests
  # doesn't stop check-cves from running
  -
    - unit-tests
    - check-cves
    - check-cve-website-state
jobs:
  unit-tests:
    series: jammy
    architectures: amd64
    packages:
      - distro-info
      - file
      - git
      - lsb-release
      - pyflakes3
      - python3
      - python3-apt
      - python3-configobj
      - python3-macaroonbakery
      - python3-mock
      - python3-progressbar
      - python3-pytest
      - python3-pytest-cov
      - python3-yaml
      - shellcheck
      - python3-dateutil
      - python3-pytest-mock
    run-before: |
      # configure a basic ~/.ubuntu-cve-tracker.conf
      echo plb_authentication=/dev/null > ~/.ubuntu-cve-tracker.conf
      export UCT=$(pwd)
      echo plb_authentication=/dev/null > ~/.ubuntu-cve-tracker.conf
      echo "packages_mirror=$HOME/mirrors/ubuntu/" >> ~/.ubuntu-cve-tracker.conf
      echo "debian_mirror=$HOME/mirrors/debian/" >> ~/.ubuntu-cve-tracker.conf
      echo "copy dummy source_map....."
      mkdir -p $HOME/mirrors/
      cp -r test/test-source-map-data $HOME/mirrors/ubuntu
    run: |
      export UCT=$(pwd)
      # some test scripts are kept outside of the scripts directory, and
      # so need PYTHONPATH set to find modules located therein
      export PYTHONPATH="${UCT}/scripts"
      # when lpcraft runs on a local users machine where embargoed already
      # exists as a symlink it won't point to anywhere so remove that and fake a
      # new one
      rm -f embargoed
      mkdir embargoed
      echo "reporting syntax issues on scripts"
      make check-syntax-scripts
      echo "Running unit tests..."
      make check-python
      rm -rf $HOME/mirrors/ubuntu
      echo "Generate coverage report"
      make coverage-python
      export STAGE_DIR=$(mktemp -d uct-coverage-XXXXXXXX)
      mv coverage/ "${STAGE_DIR}/ubuntu-cve-tracker"
      git show --no-patch HEAD > "${STAGE_DIR}/ubuntu-cve-tracker/.gitcommit"
      tar cjf uct-coverage.tar.bz2 -C "$STAGE_DIR" ubuntu-cve-tracker
    output:
      paths:
        - uct-coverage.tar.bz2
  check-cves:
    series: jammy
    architectures: amd64
    packages:
      - distro-info
      - lsb-release
      - python3
      - python3-apt
      - python3-configobj
      - python3-progressbar
      - python3-pytest
      - python3-yaml
      - rsync
      - wget
    run-before: |
      export UCT=$(pwd)
      # configure a basic ~/.ubuntu-cve-tracker.conf and setup packages-mirror
      # for source_map
      echo plb_authentication=/dev/null > ~/.ubuntu-cve-tracker.conf
      echo "packages_mirror=$HOME/mirrors/ubuntu/" >> ~/.ubuntu-cve-tracker.conf
      echo "debian_mirror=$HOME/mirrors/debian/" >> ~/.ubuntu-cve-tracker.conf
      echo "Setting up packages-mirror..."
      # use wget for packages-mirror since rsync is not accessible in lp
      # builders - also invoke with -v since this seems to make downloading more
      # reliable (probably slows down wget or somesuch to it doesn't thrash the
      # internal mirror)
      echo "./scripts/packages-mirror -w -v"
      ./scripts/packages-mirror -w -v
    run: |
      export UCT=$(pwd)
      # when lpcraft runs on a local users machine where embargoed already
      # exists as a symlink it won't point to anywhere so remove that and fake a
      # new one
      rm -f embargoed
      mkdir embargoed

      echo "Checking syntax..."
      ./scripts/check-syntax
  check-cve-website-state:
    series: jammy
    architectures: amd64
    packages:
      - distro-info
      - lsb-release
      - python3
      - python3-macaroonbakery
      - python3-requests
    run: |
      ./scripts/post-release-to-web-cve-tracker.py --action validate all

